### ISSUE TITLE
Rust Bindgen Fails

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire_rust#2]
Tried using https://github.com/crabtw/rust-bindgen but fails when pulling in ostream:

		jramapuram@gauss ~/p/a/include>
		../../rust-bindgen/target/debug/bindgen -l lib/libafcuda.dylib -I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -o arrayfire.rs arrayfire.h
		arrayfire.h:10:9: warning: #pragma once in main file
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:227:9: error: unknown type name '__char16_t'
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:228:9: error: unknown type name '__char32_t'
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:360:1: error: unknown type name 'namespace'
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:360:14: error: expected ';' after top level declarator
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:538:1: error: unknown type name 'template'
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:538:10: error: expected identifier or '('
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:539:1: error: unknown type name 'template'
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:539:10: error: expected identifier or '('
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:96:1: error: unknown type name 'namespace'
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:96:1: error: expected ';' after top level declarator
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:67:1: error: unknown type name 'namespace'
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstring:67:1: error: expected ';' after top level declarator
		/usr/include/wctype.h:122:1: error: unknown type name 'wctrans_t'
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cwctype:61:1: error: unknown type name 'namespace'
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cwctype:61:1: error: expected ';' after top level declarator
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstddef:44:1: error: unknown type name 'namespace'
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstddef:44:1: error: expected ';' after top level declarator
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/new:132:38: error: expected ';' after top level declarator
		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/new:133:30: error: variable has incomplete type 'void'
		fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by umar456** [comment]
I am not familiar with this tool. Looks like it is failing in the C++ header files. I would imagine this would also fail on other types of libraries with these errors.

**Comment by jramapuram** [comment]
Yup. It's pulling in iostream which is a cpp dependency. The best way to go in my mind for easy rust integration would be to factor our core c routines from c++ ones. This will allow for easy integration using FFI. This would also be helpful for other projects that you guys might have in mind. I.e: arrayfire java for instance. I believe NDK is much easier for c integration as opposed to c++.

**Comment by umar456** [comment]
We already try to do that with the `#ifdef __cplusplus` macros. If you don't have `__cplusplus` defined it should only include C bindings.

**Comment by jramapuram** [comment]
Yup, just some locations are missing them, eg:

  - dim4.hpp : includes vector, iostream & istream and has no header guard
  - some locations have namespaces used before a header guard, eg: image.h

There are a few others like this. I have managed to hack together a (non-tested yet) binding actually: https://github.com/jramapuram/rust_arrayfire/blob/master/arrayfire.rs

**Comment by umar456** [comment]
Could you put together a pull request with your changes? These need to be included with those header guards in the main repo.

**Comment by jramapuram** [comment]
Yup, will try to get that in within the next few days.

**Comment by jramapuram** [comment]
Ok sorry for the delay. I was going to do this today but it looks like you guys handled it already! The rust auto binding generator is very hacky right now and doesn't [parse items properly](https://github.com/jramapuram/rust_arrayfire). Maybe a test with a smaller subset would be a good first step

**Comment by pavanky** [comment]
@jramapuram We made sure our API in the 3.0 release works with C only compilers. The rust bindgen should have a lot fewer errors now. Can you give it a shot ?

**Comment by jramapuram** [comment]
@pavanky : I just did. It generates fine now! However it looks like the bindgen is [pulling in a va_list](https://github.com/jramapuram/rust_arrayfire/blob/master/src/arrayfire.rs) which is a c++ dependency:
```rust
pub type __darwin_va_list = __builtin_va_list;
```

**Comment by pavanky** [comment]
`va_list` and `__builtin_va_list` seem to come from [stdarg.h](http://en.wikipedia.org/wiki/Stdarg.h) which is a standard C header file. I don't think it is a C++ dependency.

**Comment by jramapuram** [comment]
Oh yes, you are right! It is used in printf(). Sorry, a little distracted working on my thesis.  So I got it to build the library! Will try to do a simple test today to see if it works.

**Comment by pavanky** [comment]
Alright, I am closing the issue if that is the case. Do you want to send in a PR once you have an example working ? I can give you push permissions to this library if you are interested.

**Comment by jramapuram** [comment]
Let me message you if I get it working :)
