### ISSUE TITLE
Create a Safe Rust Interface

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire_rust#5]
https://doc.rust-lang.org/book/ffi.html

**Comment by jramapuram** [comment]
@9prady9 have you ensured  there are no unsafe bindings calls?

**Comment by 9prady9** [comment]
@jramapuram the functions i added so far, i made sure to wrap them with `unsafe` blocks inside the rust wrapper functions. I can't say i am 100% certain, but based on what i read so far on FFI for rust, it seems to be correct. [This](https://doc.rust-lang.org/book/ffi.html#creating-a-safe-interface) is what i mostly followed.

**Comment by jramapuram** [comment]
Yup, you are right! This should be fine :)
